version: '3'
services:
  postgres:
    image: postgres:14
    container_name: ekristjan-pg
    ports:
      - '6500:5432'
    environment:
      - POSTGRES_DB=ekristjan
      - POSTGRES_USER=ekristjan
      - POSTGRES_HOST_AUTH_METHOD=trust
  maildev:
    image: djfarrelly/maildev
    container_name: ekristjan-mail
    ports:
      - '6080:80'
      - '6090:25'
