/*
 * This file is generated by jOOQ.
 */
package co.petrin.ekristijan.db.tables.records;


import co.petrin.ekristijan.db.tables.Activity;

import javax.annotation.Nonnull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * An after-school activity pupils may have on their schedule
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityRecord extends UpdatableRecordImpl<ActivityRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.activity.activity_id</code>.
     */
    public void setActivityId(@Nonnull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.activity.activity_id</code>.
     */
    @Nonnull
    public Integer getActivityId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.activity.name</code>. Name of the activity
     */
    public void setName(@Nonnull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.activity.name</code>. Name of the activity
     */
    @Nonnull
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Integer> field1() {
        return Activity.ACTIVITY.ACTIVITY_ID;
    }

    @Override
    @Nonnull
    public Field<String> field2() {
        return Activity.ACTIVITY.NAME;
    }

    @Override
    @Nonnull
    public Integer component1() {
        return getActivityId();
    }

    @Override
    @Nonnull
    public String component2() {
        return getName();
    }

    @Override
    @Nonnull
    public Integer value1() {
        return getActivityId();
    }

    @Override
    @Nonnull
    public String value2() {
        return getName();
    }

    @Override
    @Nonnull
    public ActivityRecord value1(@Nonnull Integer value) {
        setActivityId(value);
        return this;
    }

    @Override
    @Nonnull
    public ActivityRecord value2(@Nonnull String value) {
        setName(value);
        return this;
    }

    @Override
    @Nonnull
    public ActivityRecord values(@Nonnull Integer value1, @Nonnull String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityRecord
     */
    public ActivityRecord() {
        super(Activity.ACTIVITY);
    }

    /**
     * Create a detached, initialised ActivityRecord
     */
    public ActivityRecord(@Nonnull Integer activityId, @Nonnull String name) {
        super(Activity.ACTIVITY);

        setActivityId(activityId);
        setName(name);
    }
}
