package co.petrin.ekristijan.security
import io.vertx.ext.auth.authorization.PermissionBasedAuthorization
import io.vertx.ext.auth.jwt.JWTAuth
import io.vertx.kotlin.core.json.jsonObjectOf
import io.vertx.kotlin.coroutines.await
import io.vertx.kotlin.ext.auth.jwtOptionsOf

/*
    Password resets work like this: users can request a password reset. An email message will be sent to the user
    containing a link with an embedded JWT. This JWT will contain the users' email address as its subject and
    "reset-password" will be among its permissions.

    The system will not actually send emails to addresses in our database to prevent the app from spamming people, but
    from this app's security perspective we might as well generate those reset tokens - they will match no user in the
    database anyway.

    When a user submits a password reset request using this JWT, it will be decoded and verified. Its creation timestamp
    will be taken as its uniqueness identifier (to prevent token reuse). User will also send their new password so
    those can be hashed and stored into the database.
 */

private val resetPasswordAuthorization = PermissionBasedAuthorization.create("reset-password")

/**
 * A password reset payload, encoded as JWT. Checking the JWT signature ensures the payload was generated by us.
 * @property teacherEmail email of the teacher whose password we should reset
 * @property uniqueIdentifier A unique identifier of the token, allowing them to be used only once
 */
data class PasswordReset(val teacherEmail: String, val uniqueIdentifier: Long)

/** Generates a new password reset token */
fun generatePasswordResetToken(teacherEmail: String, expiresInMinutes: Int, jwt: JWTAuth): String {
    val props = jwtOptionsOf(
        subject = teacherEmail,
        expiresInMinutes = expiresInMinutes,
        permissions = listOf(resetPasswordAuthorization.permission),
    )
    return jwt.generateToken(jsonObjectOf(), props)
}

/**
 * Decodes a JWT password reset token.
 * Throws an exception if the signature verification had failed!
 */
suspend fun decodePasswordResetToken(token: String, jwt: JWTAuth): PasswordReset {
    val user = jwt.authenticate(jsonObjectOf("token" to token)).await()
    val uniqueToken = user.attributes().getLong(IAT_UNIQUE_PARAM)
    check(resetPasswordAuthorization.match(user)) { "Password cannot be reset using this token!" }
    return PasswordReset(teacherEmail = user.subject(), uniqueIdentifier = uniqueToken)
}