package co.petrin.ekristijan.security
import de.mkammerer.argon2.Argon2
import io.vertx.ext.auth.User
import io.vertx.ext.auth.authorization.PermissionBasedAuthorization
import io.vertx.ext.auth.jwt.JWTAuth
import io.vertx.kotlin.core.json.jsonObjectOf
import io.vertx.kotlin.coroutines.await
import io.vertx.kotlin.ext.auth.jwtOptionsOf

/*
    Password resets work like this: users can request a password reset. An email message will be sent to the user
    containing a link with an embedded JWT. This JWT will contain the users' email address as its subject and
    "reset-password" will be among its permissions.

    The system will not actually send emails to addresses in our database to prevent the app from spamming people, but
    from this app's security perspective we might as well generate those reset tokens - they will match no user in the
    database anyway.

    When a user submits a password reset request using this JWT, it will be decoded and verified.

    In addition to the signature being checked, each password reset token is also issued with a number called
    "generation". This number is stored on the user and included in all password reset tokens. As soon as a password
    reset succeeds, the user's generation is increased to this generation + 1. A password reset's generation must be
    equal to or greater to the "generation" stored on the user to work. Thus, a password reset effectively disables
    all other password resets issued up to that point (to prevent resets sent to a wrong email from continuing to work,
    for example).
 */

val RESET_PASSWORD_SCOPE = "reset-token"

/**
 * A password reset payload, encoded as JWT. Checking the JWT signature ensures the payload was generated by us.
 * @property teacherEmail email of the teacher whose password we should reset
 * @property generation A unique identifier of the token, allowing them to be used only once
 */
data class PasswordReset(val teacherEmail: String, val generation: Int)

/** Generates a new password reset token */
fun generatePasswordResetToken(teacherEmail: String, resetGeneration: Int, expiresInMinutes: Int, jwt: JWTAuth): String {
    val props = jwtOptionsOf(
        subject = teacherEmail,
        expiresInMinutes = expiresInMinutes
    )
    return jwt.generateToken(jsonObjectOf(
        "scope" to RESET_PASSWORD_SCOPE,
        "generation" to resetGeneration,
    ), props)
}

/**
 * Decodes a JWT password reset token.
 * Throws an IllegalStateException if the signature verification had failed!
 */
fun decodePasswordResetFromUser(user: User): PasswordReset {
    // -250 prevents errors in case any old password resets are still around (they should expire pretty quickly though).
    // Remove this workaround after a few days of release to prod.
    val generation = user.principal().getInteger("generation") ?: -250
    return PasswordReset(teacherEmail = user.subject(), generation = generation)
}

/** Hashes a password with some sane parameters */
fun hashPassword(password: String, passEncoder: Argon2) =
    passEncoder.hash(10, 65536, 1, password)