/*
 * This file is generated by jOOQ.
 */
package co.petrin.ekristijan.db;


import co.petrin.ekristijan.db.tables.Departure;
import co.petrin.ekristijan.db.tables.ExtraordinaryDeparture;
import co.petrin.ekristijan.db.tables.PasswordReset;
import co.petrin.ekristijan.db.tables.Pupil;
import co.petrin.ekristijan.db.tables.RegisteredDevice;
import co.petrin.ekristijan.db.tables.School;
import co.petrin.ekristijan.db.tables.Summon;
import co.petrin.ekristijan.db.tables.SummonAck;
import co.petrin.ekristijan.db.tables.Teacher;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * A record of when a pupil had left school
     */
    public static final Departure DEPARTURE = Departure.DEPARTURE;

    /**
     * A planned departure at a non-standard time about which the teacher must
     * be notified. Guaranteed there is only one extraordinary departure per
     * day!
     */
    public static final ExtraordinaryDeparture EXTRAORDINARY_DEPARTURE = ExtraordinaryDeparture.EXTRAORDINARY_DEPARTURE;

    /**
     * A password reset request
     */
    public static final PasswordReset PASSWORD_RESET = PasswordReset.PASSWORD_RESET;

    /**
     * A pupil whose departures we are tracking
     */
    public static final Pupil PUPIL = Pupil.PUPIL;

    /**
     * A device registered to receive notifications, 
     */
    public static final RegisteredDevice REGISTERED_DEVICE = RegisteredDevice.REGISTERED_DEVICE;

    /**
     * A school with pupils &amp; teachers
     */
    public static final School SCHOOL = School.SCHOOL;

    /**
     * A request for the pupil to come to the door
     */
    public static final Summon SUMMON = Summon.SUMMON;

    /**
     * The table <code>public.summon_ack</code>.
     */
    public static final SummonAck SUMMON_ACK = SummonAck.SUMMON_ACK;

    /**
     * A teacher authorized to supervise children
     */
    public static final Teacher TEACHER = Teacher.TEACHER;
}
